POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  bookCount
  allBooks(author: "Rober Martin") {title}
  allAuthors {name}
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  addBook(
    title: "Esan kirja 2",
    author:"Esa Maaninia"
    published: 2021,
    genres: ["refactoring","agile"]
  ){
    title
  	published
    genres
  }
}
