### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  bookCount
  authorCount
  allBooks { title genres }
  allAuthors {name born}
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks {
    title 
    author {name}
    genres 
    published 
  }
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks( genre:"agile") {
    title 
    genres 
    published 
  }
}
###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks(author: "Robert Martin") {
    title 
    genres 
    published 
  }
}
###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username:"Pekka Pätkä",password: "secred"){
    value
  }
}



###
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  addBook(
    title: "L",
    author: "Esa Kirjailija",
    published: 2020,
    genres: ["refactoring","agile"]
  ){
    title
    author {name}
  	published
    genres
  }
}

### EI TOIMI
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBla2thIFDDpHRrw6QiLCJpZCI6IjYwOTI2MGRkZjhmZDUwMzQ2MTg1MmNmZCIsImlhdCI6MTYyMDg0NzEyOX0.vUaWp_Zu8zKsaSvfzuacwvRP6ryL-FiowbBrWtFU7GM"

mutation {
  editAuthor(
    name: "Niilo Kirjuri",
    setBornTo: 1989
  ){
    name
    born
  }
}