### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  bookCount
  allBooks {
    title 
    author
    genres
  }
  allAuthors {name born bookCount}
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks {
    title 
    author
    genres 
    published 
  }
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks( genre:"refactoring") {
    title 
    genres 
    author
    published 
  }
}
###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  allBooks(author: "Robert Martin") {
    title 
    genres 
    published 
  }
}
###
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  addBook(
    title: "Lisätty kirja4",
    author:"Niilo Novelisti"
    published: 2021,
    genres: ["refactoring","agile"]
  ){
    title
    author 
  	published
    genres
  }
}

###
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  editAuthor(
    name: "Niilo Novelisti",
    setBornTo: 1965
  ){
    name
    born
  }
}